// Historial de actualizaciones mostrado en "Novedades". Cada `date` es la
// fecha/hora REAL del commit de git que introdujo ese cambio (obtenida con
// `git log --all --format="%H|%ad|%s" --date=iso` y emparejada a mano por
// palabras clave del propio mensaje de commit, revisando el historial
// completo antes de asignar nada — ver la respuesta que acompaña a este
// cambio para el detalle de la correspondencia y cuántas entradas se
// encontraron). Si no se encontró una coincidencia clara, `date` es `null`
// a propósito: la interfaz muestra "Fecha no disponible" en ese caso en
// vez de una fecha inventada.
export const CHANGELOG = [
  {
    id: 1,
    title: "Motor de combate por turnos",
    summary: "Combates reales turno a turno usando datos de PokeAPI, con PP, precisión y una fórmula de daño fiel a los juegos.",
    detail: "Sustituye el sistema de combate simplificado original (comparación de un solo número por Pokémon) por un sistema completo por turnos con movimientos reales, PP, precisión, velocidad y críticos.",
    // TODO: fecha no encontrada en git log — no hay ningún commit cuyo
    // mensaje mencione explícitamente la introducción de este sistema; el
    // commit inicial ("Liga de Campeones - torneo Pokémon") no tiene
    // palabras clave que lo distingan del resto del contenido inicial del
    // proyecto, así que se deja sin fecha en vez de asumir que es ese.
    date: null,
  },
  {
    id: 2,
    title: "Movesets del anime y estados",
    summary: "Cada Pokémon usa los movimientos que realmente tuvo en la serie, y los estados (parálisis, quemadura, veneno...) ya hacen efecto.",
    detail: "Se creó un moveset propio por combinación entrenador+Pokémon basado en apariciones reales del anime, y se implementó la funcionalidad completa de los efectos de estado, que antes solo consumían el turno sin hacer nada.",
    date: "2026-08-10T14:13:52+02:00",
  },
  {
    id: 3,
    title: "Descripciones de movimientos",
    summary: "El selector de movimientos ahora explica qué hace cada uno antes de elegirlo.",
    detail: "Se añadieron descripciones en español, tipo, categoría, poder, precisión y PP visibles en el selector de combate.",
    date: "2026-08-10T14:13:52+02:00",
  },
  {
    id: 4,
    title: "Corrección de tipo y objetivos de movimientos",
    summary: "Aegislash tenía el tipo mal asignado, y los movimientos de subida de stats afectaban al rival en vez de a quien los usaba.",
    detail: "Se corrigió la resolución del tipo real de Aegislash desde la API, y se arregló el sistema para que los cambios de estadísticas respeten el campo `target` real de cada movimiento (subidas propias vs bajadas al rival), incluyendo que no afecten a Pokémon inmunes por tipo.",
    date: "2026-08-10T15:34:17+02:00",
  },
  {
    id: 5,
    title: "Turno de recarga",
    summary: "Movimientos como Hiperrayo ya obligan a descansar un turno después de usarlos.",
    detail: "Se implementó la mecánica de recarga obligatoria tras movimientos de la familia Hiperrayo/Giga Impacto.",
    date: "2026-08-10T15:43:47+02:00",
  },
  {
    id: 6,
    title: "Indicadores visuales en combate",
    summary: "Ahora se ven las subidas y bajadas de estadísticas, los estados alterados, y cuántas monedas ganas exactamente al final del torneo.",
    detail: "Se añadieron indicadores con flechas/colores para stat stages y badges para estados (parálisis, quemadura...), y se sustituyó el mensaje genérico de \"ganaste monedas\" por la cifra exacta ganada.",
    date: "2026-08-10T15:58:59+02:00",
  },
  {
    id: 7,
    title: "Movimientos de furia y confusión",
    summary: "Enfado y similares bloquean varios turnos seguidos, y dejan confuso al Pokémon al terminar.",
    detail: "Se implementó el bloqueo de turnos de movimientos tipo Enfado/Danza Pétalo/Golpes Furia, con confusión automática al finalizar el bloqueo.",
    date: "2026-08-10T16:09:12+02:00",
  },
  {
    id: 8,
    title: "Límite de estadísticas -6/+6",
    summary: "Las subidas y bajadas de stats ya no pueden superar los límites reales de los juegos.",
    detail: "Se aplicó el tope de -6 a +6 en los stages de cualquier estadística modificable en combate.",
    date: "2026-08-10T18:12:20+02:00",
  },
  {
    id: 9,
    title: "Corrección del estado Dormido",
    summary: "Un Pokémon dormido ya no se despierta antes de tiempo por un error de conteo de turnos.",
    detail: "Se corrigió el desfase en el contador de turnos de sueño que hacía que el Pokémon pudiera actuar cuando no debía.",
    date: "2026-08-10T18:28:31+02:00",
  },
  {
    id: 10,
    title: "Golpes críticos justos",
    summary: "Los críticos ya ignoran correctamente solo las penalizaciones propias, no todas las estadísticas.",
    detail: "Los golpes críticos ahora ignoran bajadas de Ataque propio y subidas de Defensa rival, sin anular el resto de stages.",
    date: "2026-08-10T18:16:52+02:00",
  },
  {
    id: 11,
    title: "Cambiar de Pokémon en combate y ver efectividad",
    summary: "Ya puedes cambiar de Pokémon a mitad de combate, ver qué Pokémon quedan vivos de cada lado, y saber si un movimiento es supereficaz antes de usarlo.",
    detail: "Se añadió la opción de cambio voluntario de Pokémon durante el combate, un visor del estado del equipo completo de ambos lados, y etiquetas de efectividad de tipo (Inmune/Poco eficaz/Eficaz/Supereficaz/Hipereficaz) en el selector de movimientos.",
    date: "2026-08-10T21:32:39+02:00",
  },
  {
    id: 12,
    title: "Protección y Come Sueños",
    summary: "Protección ya falla más si se usa varias veces seguidas, y Come Sueños cura correctamente al usuario.",
    detail: "Se implementó la probabilidad decreciente de éxito de Protección en usos consecutivos, y la curación del 50% del daño en Come Sueños solo contra objetivos dormidos.",
    date: "2026-08-10T22:28:00+02:00",
  },
  {
    id: 13,
    title: "Movimientos fulminantes, golpes múltiples y Tóxico",
    summary: "Perforsión y similares ya pueden noquear de un golpe, Lanzarrocas golpea el número real de veces, y Tóxico envenena gravemente de verdad.",
    detail: "Se implementaron los movimientos OHKO con su precisión real, el retroceso (flinch), la distribución real de golpes múltiples (35/35/15/15%), y el veneno grave con daño creciente por turno en vez del veneno normal.",
    date: "2026-08-10T23:20:03+02:00",
  },
  {
    id: 14,
    title: "STAB, clima, PP visible y orden de turno",
    summary: "Se verificó el bonus de mismo tipo, se implementó el clima con sus efectos, el PP se gasta de verdad, y los cambios de Pokémon respetan el orden correcto frente a Persecución.",
    detail: "Se confirmó el cálculo de STAB, se añadió clima (Sol/Lluvia/Tormenta de Arena/Granizo) con indicador visual, PP real por movimiento, y se corrigió el orden de resolución de cambios voluntarios frente al movimiento Persecución.",
    date: "2026-08-10T23:40:54+02:00",
  },
  {
    id: 15,
    title: "Compra de entrenadores",
    summary: "Ya puedes desbloquear entrenadores con monedas de torneo, y el progreso se guarda entre sesiones.",
    detail: "Se implementó el flujo de compra de los entrenadores bloqueados con precios fijos, y se añadió persistencia en el navegador para que las monedas y compras no se pierdan al recargar la página.",
    date: "2026-08-10T22:46:48+02:00",
  },
  {
    id: 16,
    title: "Rediseño de Personajes y Tienda",
    summary: "Se simplificó la sección de Personajes y la Tienda pasó a llamarse Gatcha.",
    detail: "Se eliminó la compra directa de personajes y el gacha de entrenadores de la tienda, dejando la compra de personajes solo en Personajes, y renombrando la tienda a Gatcha.",
    date: "2026-08-10T23:50:18+02:00",
  },
  {
    id: 17,
    title: "Sistema de Gacha completo",
    summary: "Nuevo sistema de tiradas con 6 rarezas, Pokémon shiny, y una colección donde ver todo lo conseguido.",
    detail: "Se implementó el gacha general y por tipo con 481 Pokémon de última etapa evolutiva, 6 rarezas con sus probabilidades reales, reembolso por repetidos, probabilidad de shiny, y la nueva tab Pokémon con la colección del usuario.",
    date: "2026-08-11T11:04:28+02:00",
  },
  {
    id: 18,
    title: "Shiny independiente y entrenador editable",
    summary: "Los shiny ya cuentan como Pokémon distintos en la colección, y puedes editar el equipo de tu entrenador propio.",
    detail: "Los shiny pasaron a ser entradas independientes de la colección con reembolso x4 en repetidos, se hizo editable el equipo del entrenador propio, y se añadió la edición de movimientos de cualquier Pokémon de la colección.",
    date: "2026-08-11T11:36:28+02:00",
  },
  {
    id: 19,
    title: "12 entrenadores nuevos",
    summary: "Se amplió el roster con Lance, Plubio, Mirto, Alain, Sabino, Benito, Trip, Cameron, Rojo, Helio, N y Acromo, con movesets competitivos.",
    detail: "Se añadieron 12 entrenadores nuevos con sus equipos y precios, se sustituyeron todos los movesets del roster por sets competitivos, y se cambió Pikachu por Raichu en los equipos donde aparecía.",
    date: "2026-08-11T11:54:11+02:00",
  },
  {
    id: 20,
    title: "Modos de torneo e historial",
    summary: "Nuevos modos de torneo (con o sin tu entrenador propio), 5 rondas en vez de 4, y un historial con tus estadísticas.",
    detail: "Se implementaron los modos A y B de torneo, se amplió a 5 rondas, y se añadió un historial de partidas con estadísticas agregadas por modo.",
    date: "2026-08-11T23:18:30+02:00",
  },
  {
    id: 21,
    title: "Filtros en la colección",
    summary: "Ya puedes buscar tus Pokémon y movimientos por nombre, tipo, categoría o rareza.",
    detail: "Se añadieron filtros combinables en la tab Pokémon y en el selector de edición de movimientos.",
    date: "2026-08-12T23:40:06+02:00",
  },
  {
    id: 22,
    title: "Dificultades de IA y Ruleta Pokémon",
    summary: "La CPU ya tiene tres niveles de dificultad, y hay un nuevo modo de torneo con equipo completamente aleatorio.",
    detail: "Se implementaron los niveles Normal, Difícil (cambios razonados) y Maestro (simulación a 2 turnos), y el modo Ruleta Pokémon con equipo aleatorio para el usuario.",
    date: "2026-08-13T10:51:34+02:00",
  },
  {
    id: 23,
    title: "Movesets por dificultad y correcciones varias",
    summary: "La CPU en Difícil/Maestro usa equipos más optimizados, y se corrigieron varios bugs de combate (Dracoflecha, Voltiocambio, Smeargle).",
    detail: "Se separaron los movesets de la CPU según dificultad con sinergia de equipo, se permitió editar el moveset de cualquier entrenador comprado sin afectar a la CPU, y se corrigieron Dracoflecha, el orden de turno con Voltiocambio, y el movepool de Smeargle.",
    date: "2026-08-13T11:52:35+02:00",
  },
  {
    id: 24,
    title: "Corrección de Hierba Lazo",
    summary: "Ahora su daño depende realmente del peso del objetivo.",
    detail: "Se corrigió el cálculo de potencia de Hierba Lazo, que antes usaba un valor fijo casi nulo en vez de escalar con el peso real del rival.",
    date: "2026-08-12T23:30:35+02:00",
  },
  {
    id: 25,
    title: "Sistema de 50 logros",
    summary: "Nueva sección de Logros con 50 retos y recompensas de monedas por cumplirlos.",
    detail: "Se implementaron 50 logros agrupados por categoría, con seguimiento de progreso, reconstrucción retroactiva para partidas ya en curso, y recompensas escaladas en monedas.",
    date: "2026-08-13T12:14:34+02:00",
  },
  {
    id: 26,
    title: "Corrección de bugs de combate reportados",
    summary: "Mensaje de debilitamiento duplicado, Voltiocambio, Fake Out y Liofilización, todos corregidos.",
    detail: "Se corrigió que el mensaje de debilitamiento apareciera dos veces, un bug de Voltiocambio con cambios del rival, la restricción de primer turno en Fake Out/Impresión Primeriza, y la efectividad especial de Liofilización contra tipo Agua.",
    date: "2026-08-13T22:09:09+02:00",
  },
  {
    id: 27,
    title: "Emparejamientos sin revancha y Ruleta Pokémon mejorada",
    summary: "El torneo evita repetir rivales entre rondas, y en Ruleta Pokémon los rivales también tienen equipo aleatorio.",
    detail: "Se implementó la lógica para minimizar revanchas en el emparejamiento del torneo, y se amplió Ruleta Pokémon para que los 7 rivales también reciban equipos aleatorios con movesets competitivos, en vez de sus equipos fijos.",
    date: "2026-08-13T22:57:27+02:00",
  },
  {
    id: 28,
    title: "Nombres oficiales en español",
    summary: "Se corrigieron los nombres de varios entrenadores a su localización oficial.",
    detail: "Wallace pasó a llamarse Plubio, Alder a Mirto, Red a Rojo, Cyrus a Helio y Colress a Acromo, y los rivales de Ruleta Pokémon ahora usan nombres de entrenadores reales del roster.",
    date: "2026-08-13T23:23:19+02:00",
  },
  {
    id: 29,
    title: "PokéArena",
    summary: "La app tiene nuevo nombre, descripción e icono.",
    detail: "Se renombró la app de \"Liga de Campeones\" a \"PokéArena\", se actualizó el texto de cabecera, y se creó un favicon propio con el diseño de la Pokéball ya usada en la interfaz.",
    date: "2026-08-14T12:41:51+02:00",
  },
  {
    id: 30,
    title: "Congelación, movimientos de dos turnos y curación",
    summary: "Se corrigieron las inmunidades de tipo a estados, Ataque Celestial ya tarda dos turnos, y los movimientos de curación por fin funcionan.",
    detail: "Se implementaron las inmunidades de tipo a sus propios estados (Fuego no se quema, Eléctrico no se paraliza, Hielo no se congela), la mecánica completa de congelación, movimientos de carga vulnerables como Ataque Celestial, la dependencia de Rodillo de Acero de un campo activo, y los movimientos de curación/drenaje (Descanso, Recuperación, Gigadrenado).",
    date: "2026-08-14T12:23:47+02:00",
  },
  {
    id: 31,
    title: "Pokédle: stats totales en vez de rareza",
    summary: "La pista de rareza del Pokédle se sustituyó por una comparación directa de stats totales (BST).",
    detail: "La pista de Rareza (Común/Poco Común/Raro/Épico/Pseudolegendario/Legendario) del Pokédle se sustituyó por una pista de Stats Totales: compara el BST (suma de las 6 estadísticas base) del Pokémon introducido contra el del Pokémon objetivo del día, mostrando el valor exacto junto al resultado (🟩 Igual, ↑ Mayor si el objetivo tiene más stats, ↓ Menor si tiene menos), dando una pista más concreta que la rareza.",
    date: "2026-08-15T11:14:04+02:00",
  },
  {
    id: 32,
    title: "Motor de combate: nuevas familias de mecánica especial",
    summary: "El motor de combate ahora cubre muchas más mecánicas especiales, para que cualquier movimiento elegido libremente en el editor funcione correctamente, no solo los de los movesets fijos.",
    detail: "Se auditó el motor genérico (tipo, categoría, ailments, stat_changes y drenaje ya se interpretaban correctamente para cualquier movimiento) y se implementaron las familias de mecánica especial que faltaban: daño fijo (Furia Dragón, Bomba Sónica), daño por % de PS actuales del rival (Desgracia, Castigo de la Naturaleza), potencia según ratio de peso (Bofetazo Pesado, Golpe Vapor), movimientos que usan la stat del rival (Juego Sucio) o la Defensa física en vez de la Especial (Psystrike, Psyshock, Espada Sagrada), Pantallas (Pantalla de Luz/Reflejo/Velo Aurora, con indicador visual propio), hazards de entrada (Trampa Rocas, Púas, Púas Tóxicas, Telaraña), restricción de movimientos rivales (Provocación, Otra Vez, Anulación), Habitación Trampa (con indicador propio) y Relevo (hereda los stat stages al cambiar). Los golpes dobles fijos (Doble Patada, Doble Golpe, Huesoboomerang, Aguijón Doble) ya funcionaban correctamente gracias al motor genérico de golpes múltiples, sin necesitar ningún caso especial. Sustituto queda pendiente para otra sesión: su alcance real (interceptar daño, ailments y debilitamiento en casi todo el motor ya construido) no encajaba con calidad razonable en el tiempo de esta sesión.",
    date: "2026-08-17T13:11:18+02:00",
  },
  {
    id: 33,
    title: "Apodo y avatar del jugador",
    summary: "Ahora puedes configurar un apodo y un avatar, visibles en la cabecera, la clasificación del torneo y el historial de torneos.",
    detail: "Nuevo botón de perfil en la cabecera (junto a Novedades y las monedas) que abre un modal para elegir un apodo (hasta 16 caracteres) y un avatar de entre 16 emojis temáticos, con el mismo círculo de color ya usado para los avatares de entrenador del roster. En la clasificación del torneo, la fila del jugador ya no muestra solo el badge genérico 'TÚ': ahora muestra el avatar y el apodo configurados junto al nombre del entrenador con el que se está jugando esa partida. El historial de torneos también muestra el avatar y apodo del jugador junto al título del modal (una sola vez, no en cada fila, ya que todas las partidas del historial son siempre del mismo jugador local). Todo se guarda en localStorage bajo su propia clave, con el mismo patrón try/catch ya usado para monedas y entrenadores desbloqueados.",
    date: "2026-08-17T22:08:02+02:00",
  },
  {
    id: 34,
    title: "Recompensas escaladas por dificultad",
    summary: "Los torneos normales ahora dan más monedas cuanto mayor es la dificultad de la CPU: Difícil da un 50% más y Maestro las dobla.",
    detail: "La tabla de recompensa por posición final de los torneos normales (modos A, B y Ruleta Pokémon) se multiplica ahora por ×1 en Normal, ×1.5 en Difícil y ×2 en Maestro, para compensar el reto extra de las dificultades más altas (antes las tres daban exactamente las mismas monedas por la misma posición). Por ejemplo, ganar el torneo (1º puesto) pasa de dar 400 monedas siempre a dar 400/600/800 según la dificultad elegida. El selector de dificultad de la pantalla de configuración del torneo ahora muestra un indicador '×1.5'/'×2' junto a Difícil/Maestro. No afecta a ninguna otra recompensa de la app (Pokédle, recompensa diaria, gacha...).",
    date: "2026-08-17T22:49:26+02:00",
  },
  {
    id: 35,
    title: "Torneos semanales con temática",
    summary: "Nuevo modo de torneo semanal: una temática distinta cada semana (10 en total), dificultad Maestro fija, y una recompensa única de 1000 monedas la primera vez que lo ganas.",
    detail: "Nuevo 'Torneo Semanal' como cuarto modo de torneo (junto a Solo tu entrenador/Cualquier entrenador/Ruleta Pokémon): cada semana (lunes 10:00 hora de España hasta el siguiente) toca una de 10 temáticas fijas —9 de tipo (Fuego, Eléctrico, Agua, Planta, Dragón, Siniestro, Hada, Volador, Acero) y una de rareza Común— elegida de forma determinista a partir de la fecha, igual que el Pokémon del día del Pokédle, con una regla para no repetir la temática de la semana anterior. El jugador elige 6 Pokémon de su colección del gacha que cumplan la temática (filtrado en tiempo real en el selector; si no llega a 6 válidos, se indica cuántos le faltan) y combate con dificultad Maestro y emparejamiento aleatorio, ambos fijos. Se puede reintentar sin límite ni penalización mientras no se gane, pero la recompensa de 1000 monedas solo se paga la primera vez que se queda 1º esa semana; tras cobrarla, el torneo de esa semana queda bloqueado hasta la siguiente. Se integra con el historial de torneos existente (nueva categoría 'Torneo Semanal' en las estadísticas por modo) y con la clasificación, sin tocar el motor de combate.",
    date: "2026-08-18T13:21:21+02:00",
  },
  {
    id: 36,
    title: "Movesets competitivos rediseñados y modo Draft",
    summary: "Nueva lógica de generación de movesets (STAB por tipo + cobertura/recuperación/setup/estado, sin repetir Descanso/Hiperrayo/Explosión) y un nuevo modo de torneo Draft con rivales infinitos y consecuencias permanentes sobre tu colección real.",
    detail: "Se rediseñó por completo la función de moveset 'competitivo' que ya usaba Ruleta Pokémon: ahora elige un movimiento STAB por cada tipo del Pokémon (1 si es monotipo, 2 si es bitipo) priorizando fiabilidad (precisión ≥85 o nula) sobre potencia bruta, y hasta 3 huecos adicionales en orden de prioridad (cobertura de un tercer tipo, recuperación directa antes que Descanso, subida de la stat ofensiva principal, inducir un estado al rival), desprioritizando fulminantes, movimientos de carga, recarga (Hiperrayo/Giga Impacto), retroceso relevante y sacrificio propio (Explosión/Autodestrucción) sin excluirlos del todo si son la única opción real. Esta misma función alimenta ahora también el nuevo modo de torneo Draft: el jugador construye su equipo desde su colección real del gacha, confirma un aviso obligatorio de que los cambios son permanentes, y se enfrenta a rivales generados indefinidamente (nombres prestados del roster mientras queden, luego 'Desafiante N' sin límite) con equipos aleatorios del pool completo. Cada victoria da 100 monedas y obliga a un intercambio 1x1 con el equipo del rival derrotado; se puede retirar en cualquier momento tras un intercambio. Al terminar (por derrota o retirada), los Pokémon nuevos que queden en el equipo se añaden para siempre a la colección real y los originales que ya no estén se pierden para siempre, mostrando primero un resumen claro de ambas listas. Se integra con el historial de torneos (categoría 'Draft' propia). No se ha tocado el motor de combate ni los movesets fijos diseñados a mano (TRAINER_MOVESETS/TRAINER_MOVESETS_ADVANCED) ni el moveset aleatorio simple del gacha.",
    date: "2026-08-19T11:59:18+02:00",
  },
  {
    id: 37,
    title: "Corrige dos bugs del modo Draft",
    summary: "El combate del Draft ya no se reiniciaba a PS máximos a mitad de partida, y la pantalla de selección de modo ya no se quedaba visible tras empezar un Draft.",
    detail: "Bug 1: el equipo activo y el rival de cada ronda del Draft se reconstruían como objetos nuevos en cada render de DraftMode, y como la tab Torneo se sigue renderizando por motivos ajenos al Draft (el tick de la cuenta atrás del Torneo Semanal, cambios de monedas/colección...), el combate en curso volvía a prepararse desde cero cada vez que eso pasaba — se veía como si todo el equipo reviviera y se curara al máximo de la nada. Se corrigió memoizando el equipo del usuario y del rival para que mantengan la misma referencia mientras no cambien de verdad, así el combate ya no se reinicializa por error. Bug 2: la cabecera 'Elige tu entrenador' y el selector de 'Modo de torneo' seguían visibles encima de la pantalla del Draft en cuanto empezaba una partida, porque ese modo nunca cambia la fase interna del torneo normal (se queda en 'setup' a propósito, ya que Draft no usa la clasificación Swiss de siempre). Ahora DraftMode avisa a la tab Torneo en cuanto la partida está realmente en marcha, y esa cabecera/selector se ocultan por completo mientras tanto, igual que ya pasa en el resto de modos.",
    date: "2026-08-19T12:17:26+02:00",
  },
  {
    id: 38,
    title: "Explosión debilita siempre y completa la familia de Buceo",
    summary: "Explosión, Autodestrucción y similares ahora debilitan siempre a quien los usa (con una excepción de victoria si eso deja a ambos equipos sin Pokémon a la vez), y Buceo/Vuelo/Rebote/Sombra Vil ya funcionan igual que Golpe Fantasma.",
    detail: "Explosión, Autodestrucción, Detonación Confusa y Explosión Feérica (SELF_KO_MOVES) ahora debilitan siempre al usuario tras usarlas, acierte, falle o quede bloqueado por Protección — antes no tenían ningún coste real. Caso especial: si el usuario era el último Pokémon con vida de su equipo y ese mismo golpe debilita también al último Pokémon del rival, gana el RIVAL en vez de quedar en empate (el usuario se autodestruyó voluntariamente), sin tocar la regla ya existente de 'gana quien remató primero' para el retroceso normal. Se completó también la familia de movimientos de carga de dos turnos con invulnerabilidad (antes solo cubría Golpe Fantasma y Cavar): Buceo, Vuelo, Rebote y Sombra Vil comparten ahora exactamente la misma mecánica (primer turno invulnerable sin daño, segundo turno ataque automático), alcanzables tanto por el moveset competitivo/aleatorio como por el editor manual de la colección.",
    date: "2026-08-19T12:38:49+02:00",
  },
  {
    id: 39,
    title: "Badge de Novedades sin leer",
    summary: "El botón de Novedades ahora muestra cuántas entradas te faltan por leer, cada tarjeta se marca como leída al abrirla, y hay un botón para marcarlas todas de golpe.",
    detail: "Nuevo badge circular en el botón 'Novedades' de la cabecera con el número de entradas del changelog que aún no has abierto (no se muestra si no hay ninguna pendiente). Cada tarjeta sin leer se distingue con un punto de color junto al título, que desaparece en cuanto se expande para ver el detalle completo — eso ya la marca como leída, sin necesitar ninguna confirmación aparte. Dentro del propio modal hay un botón 'Marcar todo como leído' que las marca todas de golpe y hace desaparecer el badge al instante. El estado de leído/no leído se guarda en localStorage por id de entrada, así que cualquier entrada nueva que se añada en el futuro (como esta misma) aparece automáticamente como no leída para todo el mundo sin ninguna migración manual.",
    date: "2026-08-19T12:49:45+02:00",
  },
  {
    id: 40,
    title: "Dificultad en el Draft y sin duplicados al intercambiar",
    summary: "El modo Draft ya tiene selector de dificultad (Normal/Difícil/Maestro) para todos sus rivales, y avisa antes de intercambiar por una especie que ya tienes, para que no acabe duplicada en tu colección.",
    detail: "Nuevo selector de dificultad de la CPU en la pantalla de configuración del Draft (mismo Normal/Difícil/Maestro que los modos A/B/C), aplicado a todos los rivales de esa partida, con nombre prestado o 'Desafiante N'; no afecta a las 100 monedas por ronda ganada, que siguen igual. Se corrigió además un bug de duplicados: al intercambiar por un Pokémon del rival derrotado cuya especie ya tenías en tu colección real, ahora aparece un aviso antes de completar el intercambio explicando que ese Pokémon podrá usarse con normalidad el resto del Draft pero no se añadirá a la colección al terminar (para no duplicar la especie) — el usuario puede confirmar igualmente o cancelar y elegir otro. El resumen final del Draft ahora indica también qué Pokémon no se añadieron por este motivo.",
    date: "2026-08-19T12:59:47+02:00",
  },
  {
    id: 41,
    title: "El Draft se juega con tu entrenador propio",
    summary: "El modo Draft ya no empieza con una selección libre de tu colección: se juega siempre con el equipo actual de tu entrenador propio, y al terminar ese equipo se actualiza directamente con el resultado.",
    detail: "Se elimina la pantalla de selección libre de 6 Pokémon: el Draft ahora usa siempre el equipo actual del entrenador propio (deshabilitado si aún no tienes uno creado). Al terminar, el equipo del entrenador se sustituye por el equipo final del Draft en la misma operación que actualiza la colección, así que un Pokémon perdido en el Draft nunca puede quedar como referencia rota en el equipo guardado; los intercambios marcados como duplicado (excludedFromReward) apuntan a la entrada ya existente de esa especie en vez de duplicarla.",
    date: "2026-08-19T13:36:22+02:00",
  },
  {
    id: 42,
    title: "Botón para vaciar el equipo del entrenador propio",
    summary: "Nuevo botón \"Borrar equipo\" en Personajes que vacía los 6 Pokémon del entrenador propio sin borrar al entrenador ni tocar tu colección.",
    detail: "Se añade un botón destructivo \"Borrar equipo\" junto a \"Editar equipo\", con confirmación explícita antes de aplicarse. Al confirmar, el entrenador propio mantiene su nombre pero se queda sin equipo asignado hasta volver a elegir 6 Pokémon con el mismo editor ya existente; la colección del usuario no se ve afectada en ningún caso. Mientras el equipo esté vacío, el entrenador propio queda inseleccionable en Modo A y en Draft, mostrando un aviso claro en ambos sitios en vez de romperse.",
    date: "2026-08-19T13:45:41+02:00",
  },
  {
    id: 43,
    title: "Sprites reales de entrenador",
    summary: "Los 20 entrenadores del roster ahora muestran su sprite real de Pokémon Showdown en vez de un círculo con su inicial, en Personajes, el selector de Torneo y la clasificación.",
    detail: "Se añade un campo `sprite` a cada entrada de TRAINERS con la URL verificada una a una contra el índice real de play.pokemonshowdown.com/sprites/trainers/ (nunca asumida por intuición), usando siempre la variante base sin sufijo de generación cuando existe. Con sprite real: Cintia (cynthia), Máximo (steven), Dianta (diantha), Lionel (leon), Gary (blue, su nombre de juego), Iris, Ash, Lance, Plubio (wallace), Mirto (alder), Alain, Benito (barry, su nombre en el anime en inglés), Rojo (red), Helio (cyrus), N, Giovanni y Acromo (colress). Sin sprite disponible en Showdown bajo ningún nombre probado, con fallback automático al círculo de iniciales de siempre (también si la imagen llega a fallar al cargar): Paul, Sabino (Sawyer), Trip y Cameron, los cuatro exclusivos del anime sin contrapartida jugable en los juegos. Cuando un entrenador se juega con un nombre \"prestado\" (Ruleta Pokémon) o reskinado (equipo propio/semanal bajo el slot de Ash), el sprite se resuelve o se limpia junto con el nombre para no mostrar una cara que no corresponde.",
    date: "2026-08-19T18:20:34+02:00",
  },
  {
    id: 44,
    title: "Avatar de jugador con sprite de Showdown",
    summary: "Se corrige el sprite de Paul (mostraba por error a Hop) y ahora puedes usar cualquier sprite de entrenador de Pokémon Showdown como tu avatar, no solo emojis.",
    detail: "Revisado de nuevo el sprite de Paul: no existe ningún archivo \"paul.png\" ni ninguna variante con sufijo en el índice de Showdown (es un personaje exclusivo del anime sin contrapartida jugable), así que se confirma el fallback al círculo de iniciales ya implementado, sin sustituirlo por el de otro personaje. Además, el modal de perfil del jugador (apodo + avatar) gana una segunda pestaña \"Sprite de entrenador\" junto a la de \"Emoji\" de siempre: incluye accesos rápidos con los 20 sprites del roster ya validados, y un buscador libre por nombre de Showdown con vista previa en vivo (aviso claro si el nombre no existe, en vez de una imagen rota). El avatar se guarda ahora como `{ type: \"emoji\"|\"sprite\", ... }` en el mismo perfil persistido de siempre, con compatibilidad automática para perfiles guardados en el formato antiguo; se muestra correctamente (con su propio fallback si la URL deja de cargar) en la cabecera, la clasificación del torneo y el historial.",
    date: "2026-08-19T18:35:08+02:00",
  },
  {
    id: 45,
    title: "Sprite de Hop para Paul, y \"unknown\" como fallback genérico",
    summary: "Paul ya muestra un sprite real (el de Hop, sustituto elegido a mano) y los entrenadores sin sprite propio encontrado usan el sprite genérico \"unknown\" de Showdown en vez del círculo de iniciales.",
    detail: "El sprite de Paul se asigna directamente a hop.png (confirmado que carga), como sustituto visual deliberado y no un match real por nombre, ya que Showdown no tiene sprite de Paul bajo ningún nombre. Sabino (Sawyer), Trip y Cameron —los otros entrenadores del roster sin sprite propio encontrado— pasan de sprite: null (fallback a iniciales) a usar unknown.png, el sprite genérico de silueta que Showdown reserva para personajes sin sprite propio, verificado que existe y carga antes de usarlo. El círculo de iniciales se mantiene como último recurso vía el mismo onError ya implementado, por si alguna de estas URLs dejara de estar disponible en el futuro.",
    date: "2026-08-19T18:39:17+02:00",
  },
  {
    id: 46,
    title: "Sprite de Giovanni versión Let's Go",
    summary: "El sprite de Giovanni pasa a ser el de su versión en Pokémon Let's Go Pikachu/Eevee, en vez del genérico usado hasta ahora.",
    detail: "Se sustituye la URL del campo `sprite` de Giovanni por giovanni-lgpe.png (confirmado que carga correctamente), visible en Personajes, el selector de Torneo y cualquier otro sitio donde ya se mostraba su sprite anterior.",
    date: "2026-08-19T18:42:22+02:00",
  },
  {
    id: 47,
    title: "Avatar del entrenador propio sincronizado con tu perfil",
    summary: "El entrenador propio ya muestra el mismo avatar configurado en tu perfil de jugador (emoji o sprite de Showdown), en vez de un círculo con su inicial, y se actualiza solo si cambias el avatar más adelante.",
    detail: "Se sustituye el círculo de iniciales del entrenador propio por el avatar VIGENTE del perfil del jugador en Personajes, el selector de Torneo (modo A) y la clasificación del torneo, leyéndolo en cada render en vez de guardar una copia aparte: si más adelante cambias tu avatar de perfil, el entrenador propio lo refleja automáticamente en todos esos sitios sin tocar nada más. Los 20 entrenadores del roster no se ven afectados, siguen usando su propio sprite ya asignado con normalidad.",
    date: "2026-08-19T18:49:15+02:00",
  },
  {
    id: 48,
    title: "Nuevo modo: Torre Batalla",
    summary: "Combates infinitos con el equipo de cualquier entrenador desbloqueado (o el tuyo propio), con dificultad y stats del rival crecientes cada 5 rondas, y un récord personal de rondas superadas.",
    detail: "Nueva sección en la tab Torneo, sin intercambios ni consecuencias sobre tu colección (a diferencia del Draft): eliges con qué entrenador jugar (cualquiera de los desbloqueados/comprados, o tu entrenador propio si lo tienes) y te enfrentas a rivales infinitos generados igual que en el Draft. La dificultad de la IA escala cada bloque de 5 rondas (Normal 1-5, Difícil 6-10, Maestro 11+), y a partir de la ronda 16 se añade además un +5% adicional a las stats del equipo rival por cada bloque de 5 rondas superado, sin límite. Tu equipo mantiene el desgaste (PS, estados, debilitados) dentro de un mismo bloque de 5 rondas y se cura por completo justo al pasar al siguiente. Las monedas por ronda superada también escalan con la dificultad (100/150/200, +50 extra por cada bloque de boost), y puedes retirarte y cobrar después de cualquier ronda ganada. Se guarda un historial propio de partidas y un récord personal (mejor número de rondas superadas), visible antes de empezar y en vivo durante la partida — por ahora es un ranking puramente local/personal; un ranking global entre jugadores sería una ampliación futura que necesitaría infraestructura de servidor.",
    date: "2026-08-25T18:52:50+02:00",
  },
  {
    id: 49,
    title: "La Torre Batalla sube la rareza de los rivales por bloques",
    summary: "Los rivales de la Torre Batalla ya no se sortean de cualquier rareza por igual: a partir de la ronda 6 se excluyen los Comunes, de la 11 también los Poco Comunes, y desde la 16 solo aparecen especies Épicas, Pseudolegendarias o Legendarias.",
    detail: "El pool de generación de los equipos rivales (nunca el equipo del propio usuario, que sigue siendo el que él eligió) se restringe según el mismo bloque de 5 rondas ya usado para la dificultad de la IA y el boost de stats: rondas 1-5 cualquier rareza (como antes), 6-10 desde Poco Común, 11-15 desde Raro, 16 en adelante desde Épico (tope fijo, no sigue subiendo más allá). Dentro de cada bloque, el sorteo de rareza sigue las mismas probabilidades ya usadas en el resto del gacha, renormalizadas para sumar 100% solo entre las rarezas permitidas en ese bloque. La interfaz ahora indica el rango de rareza activo de los rivales (\"Rivales: Poco Común o superior\", etc.) junto al resto de información de la partida en curso.",
    date: "2026-08-25T19:17:33+02:00",
  },
  {
    id: 50,
    title: "10 logros nuevos: Torre Batalla, Draft y Torneo Semanal",
    summary: "El sistema de logros llega a 60: 4 nuevos para la Torre Batalla, 3 para el Draft y 3 para el Torneo Semanal, con sus propias categorías en la tab Logros.",
    detail: "Torre Batalla: \"Primer Ascenso\" (ronda 5), \"Al Límite\" (ronda 15), \"Sin Techo\" (ronda 30) y \"Contra Titanes\" (ganar una ronda contra un rival 100% Pseudolegendario/Legendario), desbloqueados en vivo nada más superar la ronda correspondiente. Draft: \"Coleccionista de Guerra\" (5 victorias seguidas en una misma partida), \"Trueque Constante\" (20 intercambios acumulados entre todas tus partidas) y \"Todo Tiene un Precio\" (perder 3+ Pokémon originales en una partida). Torneo Semanal: \"Especialista Semanal\" (primera victoria), \"Constancia de Hierro\" (ganar en 4 semanas distintas) y \"Maestro de Todas las Semanas\" (ganar las 10 temáticas al menos una vez). El contador de la tab Logros pasa a marcar 60/60, con tres categorías nuevas (Torre Batalla, Draft, Torneo Semanal) que siguen el mismo formato visual que las ya existentes.",
    date: "2026-08-25T19:33:51+02:00",
  },
  {
    id: 51,
    title: "Etiqueta Beta, footer y Acerca del creador",
    summary: "Nueva etiqueta \"BETA\" junto al nombre en la cabecera, un footer con los derechos de autor, y una sección \"Acerca del creador\" con contacto directo por email.",
    detail: "La cabecera muestra ahora un pequeño distintivo \"BETA\" junto a \"PokéArena\", como recordatorio visual de que el proyecto sigue en desarrollo activo. Se añade un footer discreto al final de la página con los derechos de autor (año calculado dinámicamente, nunca fijo) y un enlace a la nueva sección \"Acerca del creador\" — también accesible con un icono junto a Novedades en la cabecera —, un modal con unas palabras de Marc, el creador del proyecto, y su email de contacto como enlace mailto clicable.",
    date: "2026-08-25T19:39:19+02:00",
  },
  {
    id: 52,
    title: "Animaciones en las tiradas del gacha",
    summary: "Las tiradas del gacha ganan una Pokéball que se sacude antes de abrirse, el sprite aparece con fundido y un ligero rebote, un destello de color según la rareza, y partículas especiales para los shiny.",
    detail: "Al pulsar \"Tirar\", una Pokéball se tambalea antes de \"abrirse\" con un destello blanco: el número de sacudidas escala con la rareza ya sorteada (1 en Común, 2 en Poco Común/Raro, 3 en Épico/Pseudolegendario, 4 en Legendario), y en Legendario además se oscurece brevemente el fondo justo antes de revelar, para más expectación. El sprite conseguido aparece con un fundido y una escala con ligero rebote (en vez de aparecer de golpe), acompañado de un resplandor radial del color ya asociado a esa rareza, cuyo tamaño también crece cuanto más rara sea la tirada. La duración total de toda la secuencia va de ~0,8s en Común a ~2,4s en Legendario, sin llegar a ser tediosa al tirar varias veces seguidas ni retrasar poder volver a tirar una vez completada la revelación. Los resultados shiny suman, además, un efecto de estrellas cayendo alrededor del sprite junto a la celebración de texto ya existente.",
    date: "2026-08-27T13:42:37+02:00",
  },
  {
    id: 53,
    title: "Animaciones de inicio de combate y barra de PS",
    summary: "Cada combate empieza ahora con una pantalla de \"VS\", los Pokémon entran deslizándose al campo, y la barra de PS interpola suavemente en vez de saltar de golpe.",
    detail: "Justo al elegir el Pokémon inicial de cada combate (Draft, Torre Batalla, Torneo Semanal y los modos A/B/C, ya que todos comparten el mismo componente de combate), aparece una pantalla de \"cara a cara\": tu entrenador entra desde la izquierda, el rival desde la derecha, y un \"VS\" aparece en el centro con un efecto de escala, antes de desvanecerse y dar paso al combate real — una sola vez por combate, nunca se repite turno a turno. El sprite de cualquier Pokémon que sale al campo (al empezar el combate o tras un cambio voluntario, un debilitamiento, o cualquier entrada forzada) se desliza desde su lateral correspondiente con un ligero rebote y un destello sutil, con la misma curva de animación con rebote ya usada en las animaciones del gacha. La barra de PS ahora interpola su anchura con una transición suave (tanto al bajar como al subir) en vez de saltar al instante, y parpadea brevemente en rojo si el resultado deja al Pokémon por debajo del 20% de sus PS.",
    date: "2026-08-28T16:19:46+02:00",
  },
  {
    id: 54,
    title: "Turnos secuenciados y nuevas animaciones de combate",
    summary: "Los dos golpes de un turno ya no se ven de golpe: se reproducen uno detrás de otro, con sacudida al impactar, un efecto especial en los críticos y una caída al debilitarse.",
    detail: "Antes, aunque el motor ya resolvía correctamente quién actuaba primero según la velocidad, la interfaz aplicaba de una vez todo el resultado del turno (ambos golpes, cambios de PS y log), dando la sensación de que ocurrían a la vez. Ahora se reproduce en pasos: primero la acción de quien va más rápido, una pausa breve, luego la del más lento (si llegó a ejecutarse), y por último los efectos de fin de turno (veneno, quemadura, clima...) si los hubo, con un botón de \"Saltar animación\" para quien prefiera verlo todo de golpe. Además, el Pokémon que recibe un golpe se sacude y destella (verde si es supereficaz, gris si es poco eficaz), un golpe crítico añade un destello dorado y el texto \"¡CRÍTICO!\", y debilitarse ahora es una caída con fundido en vez de un cambio brusco a 0 PS. Entre una ronda y la siguiente del torneo (modos A/B/C y Semanal) aparece también un breve rótulo \"Ronda X de Y\" antes de mostrar la clasificación actualizada.",
    date: "2026-08-28T17:03:49+02:00",
  },
  {
    id: 55,
    title: "Copia de seguridad y equipos compartidos",
    summary: "Exporta e importa tu partida completa como archivo, y comparte tu equipo con un código que otra persona puede adoptar con sus propios Pokémon.",
    detail: "Un nuevo botón en la cabecera abre \"Copia de seguridad\": exporta toda tu partida (monedas, colección, entrenadores, logros, historial...) a un archivo .json descargable, o importa uno guardado previamente, con confirmación explícita antes de sobrescribir la partida actual y sin tocar nada si el archivo está corrupto. Además, desde la pestaña Personajes tu entrenador propio puede generar un código compacto de su equipo (especies + movimientos, sin shiny) con \"Compartir equipo\", y cualquier otra persona puede pegarlo con \"Adoptar equipo compartido\": la app comprueba si ya tiene esas 6 especies en su colección, muestra cuáles le faltan por nombre si no las tiene todas, y si las tiene completas puede adoptar el equipo usando SUS PROPIOS Pokémon de esas especies con los mismos movimientos — nunca transfiere ningún Pokémon ajeno.",
    date: "2026-08-28T17:24:35+02:00",
  },
  {
    id: 56,
    title: "Hasta 5 entrenadores propios, con nombre editable",
    summary: "Ahora puedes crear hasta 5 entrenadores propios en vez de uno solo, y ya puedes cambiarles el nombre después de creados.",
    detail: "La pestaña Personajes muestra ahora una tarjeta por cada entrenador propio que hayas creado (hasta 5), cada una con sus propios botones de \"Editar equipo\", \"Editar nombre\" (nuevo), \"Compartir equipo\" y \"Borrar equipo\", más un nuevo \"Eliminar entrenador\" para quitarlo por completo y liberar hueco. Si ya tienes uno guardado de antes de este cambio, se ha migrado automáticamente al primero de la lista sin perder nada. El resto de modos que usaban \"tu entrenador propio\" ahora dejan elegir CUÁL de los tuyos usar: el Modo A del torneo y el Draft muestran un selector cuando tienes más de uno, y la Torre Batalla los lista todos junto al resto de entrenadores desbloqueados. Ninguno de tus entrenadores propios puede aparecer nunca como rival de la CPU, en ningún modo.",
    date: "2026-08-28T17:54:20+02:00",
  },
  {
    id: 57,
    title: "Corrige referencias colgadas al equipo semanal",
    summary: "Si un Pokémon de tu equipo del torneo semanal se perdía para siempre en el Draft, el selector seguía contándolo como elegido y bloqueaba poder elegir otro en su lugar.",
    detail: "Cuando un Pokémon que ya formaba parte del equipo elegido para el Torneo Semanal se perdía de forma permanente (por ejemplo, al intercambiarlo en el Draft), el contador seguía marcando \"6/6\" con solo 5 casillas reales marcadas, y no dejaba elegir un sustituto porque esa referencia ya no correspondía a ningún Pokémon real. Ahora el selector de equipo semanal descarta automáticamente cualquier Pokémon seleccionado que ya no exista en la colección al contar y validar el equipo, y una nueva rutina se ejecuta en cuanto el Draft elimina Pokémon de la colección para limpiar esa misma referencia colgada en el equipo semanal ya confirmado, sin tocar el mecanismo ya existente que sincroniza el equipo de los entrenadores propios con el resultado del Draft.",
    date: "2026-08-30T11:12:58+02:00",
  },
  {
    id: 58,
    title: "Nuevas mecánicas de movimientos (tanda 1 de 3)",
    summary: "Semilla Drenadora, Contraataque/Copión/Explosión de Metal, aprisionamiento, Premonición/Deseo Oculto y Refugio/Aromaterapia ya funcionan de verdad en combate.",
    detail: "Tras la auditoría de cobertura de movimientos, se implementan las 5 familias de mayor impacto: Semilla Drenadora (leech-seed) ya drena PS de verdad cada turno, con inmunidad para los Pokémon de tipo Planta; Contraataque, Copión y Explosión de Metal devuelven el doble (o ×1.5) del daño físico/especial recibido ese mismo turno, fallando si no se recibió ninguno; los movimientos de aprisionamiento (Bind, Envoltura, Giro Fuego, Enterrar, Remolino, Constricción, Plaga, Tormenta Ígnea, Jaula de Trueno) atrapan al objetivo 4-5 turnos con daño residual; Premonición y Deseo Oculto ya golpean de forma diferida 2 turnos después, a quien esté en esa posición del campo en ese momento, en vez de hacer daño instantáneo; y Refugio protege a todo un equipo de nuevos problemas de estado y confusión durante 5 turnos, mientras que Aromaterapia y Campanacura curan el estado del Pokémon activo. Quedan pendientes para tandas futuras las familias de impacto medio y bajo ya identificadas en la auditoría (movimientos basados en PS actual, curación de estado en equipo completo, copia de movimientos, etc.).",
    date: "2026-08-30T21:15:53+02:00",
  },
  {
    id: 59,
    title: "Nuevas mecánicas de movimientos (tanda 2 de 3)",
    summary: "Frustración/Envite Miedo/Erupción/Surtidor/Desgaste/Garra Brutal, Sujeción/Rizo Enrollado/Anillo Hidro, Puño Firme, Maldición y Corte Furia/Rodada ya funcionan de verdad en combate.",
    detail: "Continuando la auditoría de cobertura de movimientos, se implementan las 5 familias siguientes por impacto: Frustración y Envite Miedo ganan potencia por tramos cuanto menos PS le queda al usuario, mientras que Erupción y Surtidor la pierden de forma proporcional a su PS actual, y Desgaste y Garra Brutal escalan según el PS actual del OBJETIVO; Sujeción, Bloqueo y Telaraña ya impiden que Cola Dragón/Giro Vil fuercen la salida del objetivo atrapado, y Rizo Enrollado añade ese mismo anclaje además de curar 1/16 de PS máximo cada turno (Anillo Hidro cura igual pero sin anclaje); Puño Firme ya falla de verdad si su usuario recibe un golpe antes de ejecutarlo; Maldición aplica su mecánica doble según el tipo de quien la usa (sacrificio de PS propio + daño residual al objetivo si es tipo Fantasma, o subida de Ataque/Defensa y bajada de Velocidad para cualquier otro tipo); y Corte Furia dobla su potencia con cada uso consecutivo que conecta, mientras que Rodada y Bola Hielo hacen lo mismo en una cadena forzada de 5 turnos. Quedan pendientes para la tanda final las familias de menor impacto ya identificadas en la auditoría (Reserva/Tragar/Escupir, Destino Ligado/Cántico Mortal, copia de movimientos, eliminación de hazards, etc.).",
    date: "2026-08-30T21:39:36+02:00",
  },
  {
    id: 60,
    title: "Nuevas mecánicas de movimientos (tanda 3 de 3): auditoría completa",
    summary: "Reserva/Tragar/Escupir, Destino Ligado/Cántico Mortal, Alma Cúmulo/Castigo/Magnitud/Sorpresa, Mímico/Esquema/Metrónomo/Ayuda/Sonámbulo/Movimiento Espejo/Primero, Neblina/Giro Rápido y roturas de invulnerabilidad ya funcionan de verdad en combate — con esto quedan completadas las 16 familias de la auditoría original.",
    detail: "Última tanda de la auditoría de cobertura de movimientos: Reserva acumula hasta 3 niveles subiendo Defensa/Defensa Especial, que Tragar consume curando PS o Escupir consume haciendo daño (potencia según el nivel acumulado); Destino Ligado debilita a quien remata a su usuario si este se debilita antes de volver a actuar, y Cántico Mortal pone una cuenta atrás de 3 turnos a ambos Pokémon activos que termina debilitándolos salvo que salgan del campo antes; Alma Cúmulo/Rey de la Cúspide y Castigo escalan su potencia según las etapas de stat positivas acumuladas (propias o del objetivo), y Magnitud/Sorpresa usan las tablas de potencia aleatoria oficiales; Mímico copia temporalmente el último movimiento del objetivo (se pierde al cambiar) y Esquema lo aprende para el resto del combate, Metrónomo ejecuta un movimiento al azar de todo el juego, Movimiento Espejo repite el último movimiento dañino del objetivo, Ayuda y Sonámbulo ejecutan un movimiento al azar del propio moveset (Ayuda simplificado a esto en vez de un compañero de equipo, ver el comentario de ASSIST_MOVES en el código) y Primero roba con ×1.5 de potencia el movimiento que el rival iba a usar si se actúa antes que él; Neblina y Giro Rápido eliminan los hazards de entrada acumulados; y Placaje Aéreo/Tornado/Terremoto/Magnitud/Surf/Remolino ya atraviesan con el doble de daño la invulnerabilidad de Vuelo/Rebote/Cavar/Buceo, mientras que Rayo/Vendaval/Ventisca ajustan su precisión según el clima activo (Lluvia/Sol/Granizo). Con estas 6 familias se completan las 16 identificadas en la auditoría original: las 5 de mayor impacto (tanda 1), las 5 siguientes (tanda 2) y estas últimas 6 de menor impacto o mayor coste arquitectónico, quedando fuera de alcance únicamente las mecánicas explícitamente descartadas desde el principio (dependientes de objetos, habilidades, combates dobles, amistad o género).",
    date: "2026-08-30T22:04:10+02:00",
  },
  {
    id: 61,
    title: "Nueva sección: Casino",
    summary: "Estrena la tab Casino con su primer juego, la Ruleta de la Fortuna: un giro gratis al día y giros de pago por monedas, con premios de monedas, tiradas gratis del gacha y un JACKPOT.",
    detail: "Nueva tab Casino (junto a Torneo/Personajes/Pokémon/Gatcha/Diario/Logros) pensada para alojar varios minijuegos de azar; por ahora incluye la Ruleta de la Fortuna, con espacio ya preparado para Tragaperras y Cartas Rasca más adelante. La ruleta tiene 8 casillas con las mismas probabilidades tanto en el giro gratis (uno al día, mismo reset de las 10:00 hora de Madrid que el Pokédle/recompensa diaria) como en los giros de pago (150 monedas, sin límite diario): nada (20%), 20/50/100/200/500 monedas (20/20/15/12/4%), una tirada gratis del gacha general (8%, acreditada como crédito usable sin coste en la tab Gatcha) y el JACKPOT de 1000 monedas (1%). La ruleta se dibuja como un disco de 8 sectores con gradiente cónico y gira varias vueltas con desaceleración progresiva hasta detenerse exactamente en el premio ya sorteado de antemano, con un breve destello al parar y una celebración de partículas más notoria si toca el JACKPOT.",
    date: "2026-08-31T20:35:28+02:00",
  },
  {
    id: 62,
    title: "Nuevo juego del Casino: Tragaperras",
    summary: "Segundo juego de la tab Casino: apuesta libre entre 10 y 1000 monedas, 3 carretes con símbolos elementales y Pokéball, y celebración especial para el premio gordo de 3 Pokéballs.",
    detail: "La Tragaperras deja elegir libremente cuánto apostar por tirada (mínimo 10, máximo 1000, sin poder superar el saldo disponible) y gira 3 carretes independientes con 6 símbolos posibles cada uno: los 5 tipos elementales (Fuego/Agua/Planta/Eléctrico/Normal, con los colores de tipo ya usados en el resto de la app) y la Pokéball como comodín de mayor premio. Premios: 3 Pokéballs iguales pagan x20 la apuesta (premio gordo), 3 elementales iguales pagan entre x6 y x10 según el símbolo (Fuego x10, Agua x9, Planta x8, Eléctrico x7, Normal x6), y una pareja de 2 símbolos iguales en cualquier combinación de los 3 carretes paga x1.5 (elementales) o x2 (pareja de Pokéball) — sin ninguna coincidencia se pierde toda la apuesta. Probabilidades asignadas a cada símbolo por carrete: 18% cada uno de los 5 elementales y 10% la Pokéball (suman 100%), calculadas para que el valor esperado de una tirada sea aproximadamente el 90% de la apuesta — un margen de la casa de ≈9,5%, verificado tanto analíticamente como con una simulación de 2 millones de tiradas (RTP resultante: 90,54%). Los 3 carretes giran con una animación de scroll vertical que desacelera progresivamente y se detienen uno tras otro con 400ms de desfase entre cada uno, con un destello simple para una pareja, uno más notorio para 3 elementales iguales, y la misma celebración de partículas ya usada para el JACKPOT de la Ruleta de la Fortuna si toca el premio gordo de 3 Pokéballs.",
    date: "2026-08-31T21:00:48+02:00",
  },
];

// Orden mostrado en la interfaz: de más reciente a más antigua por fecha
// real; las entradas sin fecha encontrada (`date: null`) se colocan al
// FINAL, por debajo de todas las fechadas, ya que no hay forma fiable de
// saber dónde encajarían cronológicamente sin inventar un dato.
export function getSortedChangelog() {
  return [...CHANGELOG].sort((a, b) => {
    if (a.date == null && b.date == null) return 0;
    if (a.date == null) return 1;
    if (b.date == null) return -1;
    return new Date(b.date) - new Date(a.date);
  });
}
